# Generated by Django 2.1.3 on 2018-11-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMascota', models.CharField(max_length=20)),
                ('razaMascota', models.CharField(default='', max_length=30)),
                ('descripcionMascota', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(default='Rescatados', max_length=20)),
            ],
        ),
    ]
