# Generated by Django 2.1.3 on 2018-11-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(max_length=20),
        ),
    ]
