# Generated by Django 2.1.3 on 2018-11-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('Administrador', 'Administrador'), ('Adoptante', 'Adoptante'))},
        ),
    ]
