# Generated by Django 2.1 on 2018-11-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20181108_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='run',
            field=models.CharField(default='', max_length=20),
        ),
    ]
