# Generated by Django 2.1 on 2018-11-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20181108_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotoMascota',
            field=models.ImageField(default='', upload_to='mascotas/'),
        ),
    ]
