# Generated by Django 2.1.3 on 2018-11-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20181108_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='run',
        ),
    ]
