# Generated by Django 2.1.3 on 2018-11-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20181108_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(default='Metropolitana', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vivienda',
            field=models.CharField(default='', max_length=20),
        ),
    ]
